<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Roster.ServiceDefaults\Roster.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Roster.Infrastructure\Roster.Infrastructure.csproj" />
    <ProjectReference Include="..\Roster.Application\Roster.Application.csproj" />
    <ProjectReference Include="..\Roster.Plugins.Csv\Roster.Plugins.Csv.csproj" />
    <ProjectReference Include="..\Roster.Plugins.Sessionize\Roster.Plugins.Sessionize.csproj" />
    <ProjectReference Include="..\Roster.DomainPacks\Roster.DomainPacks.csproj" />
    <ProjectReference Include="..\Roster.Web.Client\Roster.Web.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Net.Codecrete.QrCodeGenerator" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
